#!/usr/bin/env bash
# Read-only H20 environment and benchmark failure diagnostic.
# Usage: bash diagnose_h20_env_and_run.sh [matrix-session-directory]

set -uo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)
MODEL_NAME=dsv3p1_g8_sim_hess_no_mean_subtract

infer_gqla_root() {
    local session=${1:-} probe
    if [[ "$session" == */outputs/benchmarks/* ]]; then
        printf '%s\n' "${session%%/outputs/benchmarks/*}"
        return 0
    fi
    probe=$SCRIPT_DIR
    while [[ "$probe" != / ]]; do
        if [[ -f "$probe/outputs/convert/$MODEL_NAME/config.json" ]]; then
            printf '%s\n' "$probe"
            return 0
        fi
        probe=$(dirname "$probe")
    done
    if [[ -f "/mnt/public03/task/236362/GQLA/outputs/convert/$MODEL_NAME/config.json" ]]; then
        printf '%s\n' /mnt/public03/task/236362/GQLA
    else
        printf '%s\n' /mnt/tidalfs-alwl01/task/236362/GQLA
    fi
}

latest_session() {
    local root=$1 latest
    latest=$(find "$root" -mindepth 1 -maxdepth 1 -type d \
        -printf '%T@\t%p\n' 2>/dev/null \
        | sort -nr \
        | head -n1 \
        | cut -f2-)
    [[ -n "$latest" ]] || return 1
    printf '%s\n' "$latest"
}

pass() {
    echo "[PASS] $*"
}

fail() {
    echo "[FAIL] $*" >&2
}

warn() {
    echo "[WARN] $*" >&2
}

SESSION_ARG=${1:-}
GQLA_ROOT=${GQLA_ROOT:-$(infer_gqla_root "$SESSION_ARG")}
MODEL_DIR=${MODEL_DIR:-$GQLA_ROOT/outputs/convert/$MODEL_NAME}
BENCHMARK_ROOT=${BENCHMARK_ROOT:-$GQLA_ROOT/outputs/benchmarks/dsv3p1_g8_h20_tp8_all}
SESSION_DIR=$SESSION_ARG
if [[ -z "$SESSION_DIR" ]]; then
    SESSION_DIR=$(latest_session "$BENCHMARK_ROOT" || true)
fi

echo "H20_DIAGNOSTIC_BEGIN"
echo "gqla_root=$GQLA_ROOT"
echo "model_dir=$MODEL_DIR"
echo "session_dir=${SESSION_DIR:-none}"
echo "cuda_visible_devices=${CUDA_VISIBLE_DEVICES:-all}"

run_ok=1
manifest_file=
manifest_python=
if [[ -z "$SESSION_DIR" || ! -d "$SESSION_DIR" ]]; then
    fail "benchmark session directory was not found"
    run_ok=0
else
    matrix_file=$SESSION_DIR/matrix.tsv
    launcher_log=$SESSION_DIR/launcher.log
    echo
    echo "===== TOP-LEVEL MATRIX ====="
    if [[ -s "$matrix_file" ]]; then
        cat "$matrix_file"
        if awk -F '\t' 'NR > 1 && $3 !~ /^verified$/ {bad=1} END {exit bad ? 0 : 1}' \
            "$matrix_file"; then
            fail "matrix contains a failed or non-verified case"
            run_ok=0
        else
            pass "every recorded matrix row is verified"
        fi
    else
        fail "missing or empty matrix: $matrix_file"
        run_ok=0
    fi

    if [[ -s "$launcher_log" ]] \
        && grep -q -- 'H20_ALL_BENCHMARK_OK' "$launcher_log"; then
        pass "matrix launcher wrote H20_ALL_BENCHMARK_OK"
    else
        fail "matrix launcher did not reach H20_ALL_BENCHMARK_OK"
        run_ok=0
    fi

    manifest_file=$(find "$SESSION_DIR" -type f -name manifest.env \
        -printf '%T@\t%p\n' 2>/dev/null \
        | sort -nr \
        | head -n1 \
        | cut -f2-)
    if [[ -n "$manifest_file" ]]; then
        manifest_python=$(sed -n 's/^python=//p' "$manifest_file" | head -n1)
        echo "manifest=$manifest_file"
        echo "manifest_python=${manifest_python:-missing}"
    else
        warn "no nested manifest.env was written before the failure"
    fi
fi

# Prefer an explicit VENV_DIR, then the exact Python recorded by the failed
# run, then the clean cu129 environment, and finally the legacy environment.
if [[ -n "${VENV_DIR:-}" ]]; then
    PYTHON=${PYTHON:-$VENV_DIR/bin/python}
elif [[ -n "$manifest_python" && -x "$manifest_python" ]]; then
    PYTHON=$manifest_python
    VENV_DIR=$(cd "$(dirname "$PYTHON")/.." 2>/dev/null && pwd -P)
elif [[ -x "$GQLA_ROOT/envs/h20-cu129-py312/bin/python" ]]; then
    VENV_DIR=$GQLA_ROOT/envs/h20-cu129-py312
    PYTHON=$VENV_DIR/bin/python
else
    VENV_DIR=$GQLA_ROOT/envs/venv-py312
    PYTHON=${PYTHON:-$VENV_DIR/bin/python}
fi
RUNTIME_ENV_FILE=${RUNTIME_ENV_FILE:-$VENV_DIR/h20-runtime.env}

echo
echo "===== ENVIRONMENT PREFLIGHT ====="
echo "venv_dir=$VENV_DIR"
echo "python=$PYTHON"
echo "runtime_env=$RUNTIME_ENV_FILE"

env_ok=1
if [[ ! -x "$PYTHON" ]]; then
    fail "Python is missing or not executable: $PYTHON"
    env_ok=0
else
    if (
        if [[ -f "$RUNTIME_ENV_FILE" ]]; then
            # Generated by the GQLA bootstrap/setup script.
            # shellcheck disable=SC1090
            source "$RUNTIME_ENV_FILE"
        fi
        export PYTHONPATH="${GQLA_REPO:-$GQLA_ROOT/code/GQLA_preprint}${PYTHONPATH:+:$PYTHONPATH}"
        export CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-0,1,2,3,4,5,6,7}
        "$PYTHON" - "$MODEL_DIR" <<'PY'
import json
import sys
from importlib.metadata import PackageNotFoundError, version
from pathlib import Path

model_dir = Path(sys.argv[1])
failures = []


def record_failure(message, exc=None):
    if exc is not None:
        message = f"{message}: {type(exc).__name__}: {exc}"
    failures.append(message)
    print(f"ENV_CHECK_FAIL {message}")


print(f"python_executable={sys.executable}")
print(f"python_version={sys.version.split()[0]}")
for package in ("torch", "vllm", "transformers", "gqla", "hpc-ops"):
    try:
        print(f"package_{package}={version(package)}")
    except PackageNotFoundError:
        record_failure(f"package is not installed: {package}")

try:
    import torch

    print(f"torch_version={torch.__version__}")
    print(f"torch_cuda_build={torch.version.cuda}")
    available = torch.cuda.is_available()
    print(f"cuda_available={available}")
    count = torch.cuda.device_count()
    print(f"cuda_device_count={count}")
    if not available:
        record_failure("torch.cuda.is_available() is false")
    if count < 8:
        record_failure(f"expected at least 8 visible GPUs, found {count}")
    for device in range(min(count, 8)):
        name = torch.cuda.get_device_name(device)
        capability = torch.cuda.get_device_capability(device)
        print(f"gpu_{device}={name};capability={capability}")
        if capability != (9, 0):
            record_failure(f"GPU {device} capability is {capability}, expected SM90")
        with torch.cuda.device(device):
            torch.empty(1, device=f"cuda:{device}")
            torch.cuda.synchronize(device)
except Exception as exc:
    record_failure("Torch/CUDA initialization failed", exc)

try:
    import src.vllm_register_dsv  # noqa: F401
    from vllm import ModelRegistry

    registered = set(ModelRegistry.get_supported_archs())
    required = {"DeepseekV3GQLAForCausalLM", "DeepseekV3GQLAHPCForCausalLM"}
    missing = sorted(required - registered)
    print(f"vllm_required_architectures_registered={not missing}")
    if missing:
        record_failure(f"missing vLLM architecture registrations: {missing}")
except Exception as exc:
    record_failure("GQLA vLLM plugin import/registration failed", exc)

try:
    import hpc

    schema = str(torch.ops.hpc.attention_decode_bf16.default._schema)
    print(f"hpc_module={Path(hpc.__file__).resolve()}")
    print(f"hpc_decode_schema={schema}")
    if "softmax_scale" not in schema:
        record_failure("HPC-Ops decode schema lacks runtime softmax_scale")
except Exception as exc:
    record_failure("HPC-Ops import/schema check failed", exc)

try:
    required_files = (
        "config.json",
        "model.safetensors.index.json",
        "tokenizer.json",
        "tokenizer_config.json",
    )
    missing_files = [name for name in required_files if not (model_dir / name).is_file()]
    if missing_files:
        record_failure(f"converted model is missing files: {missing_files}")
    else:
        with (model_dir / "model.safetensors.index.json").open(encoding="utf-8") as handle:
            index = json.load(handle)
        shards = sorted(set(index["weight_map"].values()))
        missing_shards = [name for name in shards if not (model_dir / name).is_file()]
        print(f"checkpoint_unique_shards={len(shards)}")
        print(f"checkpoint_missing_shards={len(missing_shards)}")
        if missing_shards:
            record_failure(f"checkpoint has missing shards: {missing_shards[:8]}")
except Exception as exc:
    record_failure("checkpoint integrity check failed", exc)

if failures:
    print(f"H20_ENV_CHECK_FAILED count={len(failures)}")
    raise SystemExit(1)
print("H20_ENV_CHECK_OK")
PY
    ); then
        pass "Python/Torch/CUDA/vLLM/GQLA/HPC/checkpoint preflight passed"
    else
        fail "environment preflight failed"
        env_ok=0
    fi
fi

if [[ -n "$SESSION_DIR" && -d "$SESSION_DIR" ]]; then
    echo
    echo "===== FAILURE CLASSIFICATION ====="
    if grep -RqiE --include='*.log' \
        'driver on your system is too old|torch cannot initialize CUDA' "$SESSION_DIR"; then
        echo "likely_root_cause=CUDA driver/runtime incompatibility"
    elif grep -RqiE --include='*.log' \
        'CUDA out of memory|torch.OutOfMemoryError|out of memory' "$SESSION_DIR"; then
        echo "likely_root_cause=GPU or host memory exhaustion"
    elif grep -RqiE --include='*.log' \
        'No space left on device|Disk quota exceeded' "$SESSION_DIR"; then
        echo "likely_root_cause=filesystem space or quota exhaustion"
    elif grep -RqiE --include='*.log' \
        'No such file or directory.*cmake|cmake: command not found' "$SESSION_DIR"; then
        echo "likely_root_cause=missing CMake build tool"
    elif grep -RqiE --include='*.log' \
        'Engine core initialization failed|EngineCore failed to start' "$SESSION_DIR"; then
        echo "likely_root_cause=vLLM engine initialization failure; inspect server.log traceback below"
    elif grep -RqiE --include='*.log' \
        'timed out|TimeoutError|startup timeout' "$SESSION_DIR"; then
        echo "likely_root_cause=server startup or distributed-operation timeout"
    elif grep -RqiE --include='*.log' \
        'Killed|SIGKILL|exit code 137|returncode: -9' "$SESSION_DIR"; then
        echo "likely_root_cause=process was externally killed, commonly host OOM or pod eviction"
    elif grep -RqiE --include='*.log' \
        'benchmark result failed completeness|failed=[1-9]' "$SESSION_DIR"; then
        echo "likely_root_cause=benchmark requests failed or result was incomplete"
    else
        echo "likely_root_cause=not matched automatically; use the error excerpts below"
    fi

    echo
    echo "===== ERROR EXCERPTS (last 200 matches) ====="
    grep -RInE --include='*.log' \
        'Traceback|ERROR|Error|error:|Exception|RuntimeError|ValueError|AssertionError|OutOfMemory|out of memory|No space left|Killed|SIGKILL|failed|timed out|Timeout|Connection refused|NCCL WARN' \
        "$SESSION_DIR" 2>/dev/null \
        | tail -n 200 || true

    mapfile -t diagnostic_logs < <(find "$SESSION_DIR" -type f \
        \( -name server.log -o -name bench.log -o -name launcher.log \) \
        -print 2>/dev/null | sort)
    for log_file in "${diagnostic_logs[@]}"; do
        echo
        echo "===== TAIL: $log_file ====="
        tail -n 100 "$log_file" 2>/dev/null || true
    done
fi

echo
if (( env_ok == 1 )); then
    echo "ENV_STATUS=PASS"
else
    echo "ENV_STATUS=FAIL"
fi
if (( run_ok == 1 )); then
    echo "RUN_STATUS=PASS"
else
    echo "RUN_STATUS=FAIL"
fi
echo "H20_DIAGNOSTIC_END"

if (( env_ok == 1 && run_ok == 1 )); then
    exit 0
fi
exit 1
